import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import { motion, AnimatePresence } from 'framer-motion'
import { AuthContext } from '../src/Components/Context'
import SignUpForm from '../src/Components/SignUpForm'
import LoginForm from '../src/Components/LoginForm'


function Authentication() {

    const [tab, setTab] = useState("Sign Up")

    const [auth, setAuth] = useContext(AuthContext)


    useEffect(() => {
        if (auth) {
            router.push("/")
        }
    }, [auth])


    const handleForm = (e) => {
        e.preventDefault()
        setAuth(true)
    }

    const handleTab = () => {
        console.log(tab)
        switch (tab) {
            case "Sign Up":
                return (
                    <AnimatePresence>
                        {
                            tab === "Sign Up" && (
                                <SignUpForm handleForm={handleForm} />
                            )
                        }
                    </AnimatePresence>
                )
            case "Sign In":
                return (
                    <AnimatePresence>
                        {
                            tab === "Sign In" && (
                                <LoginForm handleForm={handleForm} />
                            )
                        }
                    </AnimatePresence>

                )
            default:
                break;
        }
    }

    return (
        <div className='w-full h-screen  bg-slate-500/50 pt-40 p-10' >
            <Head>
                <title>Auth</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.main
                layout
                data-isOpen={tab === "Sign Up"}
                className='p-10 flex flex-col items-center gap-5 w-full h-fit bg-white relative rounded-md'  >
                <h2>
                    {tab === "Sign In" ? "Sign In" : "Sign Up"}
                </h2>
                {handleTab()}
                <div>
                    {
                        tab === "Sign Up" ? (
                            <p className='flex gap-2' onClick={() => setTab("Sign In")} >
                                Signed up already ?
                                <span>
                                    Sign In
                                </span>
                            </p>
                        ) : (
                            <p className='flex gap-2' onClick={() => setTab("Sign Up")} >
                                Not a customer yet ?
                                <span >
                                    Sign Up
                                </span>
                            </p>
                        )
                    }
                </div>
            </motion.main >
        </div >
    )
}

export default Authentication
