import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Button from '../src/Components/Button'
import AnchorLink from '../src/Components/AnchorLink'

function Index() {
  return (
    <div className='w-full h-screen bg-gray-300/30' >
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-full flex flex-col justify-center items-center p-10 relative' >
        <div className='w-full h-fit text-center flex flex-col justify-center items-center gap-5' >
          <h6 className='font-semibold text-gray-500' >
            Pharmacy Dashboard
          </h6>
          <h3 className='font-bold '>
            Handle all your Pharmacy sales and transaction here
          </h3>
          <AnchorLink route="/authentication">
            <Button style="primary__btn" >
              Get Started
            </Button>
          </AnchorLink>
          <div className='w-full h-40vh relative rounded-md overflow-hidden' >
            <Image src='/landing.png' layout='fill' alt='Pharmacy Landing Page' className='object-contain' />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Index