import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect, useState } from 'react'
import Button from '../src/Components/Button'
import { AuthContext } from '../src/Components/Context'
import OrderCard from '../src/Components/OrderCard'

export default function Index() {

  const [tab, setTab] = useState("New")
  const { user } = useContext(AuthContext)

  const router = useRouter()

  const orders = {
    New: [
      {
        name: "Nivea Lotion",
        price: 4.99
      },
      {
        name: "Detol Bath",
        price: 1.23
      },
      {
        name: " Madar Soap",
        price: 0.59
      }
    ],
    Reservation: [
      {
        name: "Sanitisor",
        price: 3.98
      },
      {
        name: "Detol Bath",
        price: 1.23
      },
      {
        name: "Nose mask",
        price: 0.22
      }
    ],
    Completed: [
      {
        name: "Daipers",
        price: 2.98
      },
      {
        name: "Detol Bath",
        price: 1.23
      },
      {
        name: "baby wipe",
        price: 0.25
      }
    ],
    Cancelled: [
      {
        name: "Daipers",
        price: 2.98
      },
      {
        name: "Detol Bath",
        price: 1.23
      },
      {
        name: "baby wipe",
        price: 0.25
      }
    ],
  }

  const handleTab = () => {
    switch (tab) {
      case "New":
      case "Reservation":
      case "Completed":
      case "Cancelled":
        return (
          <>
            {
              orders[tab].map((order, index) => (
                <OrderCard detail={order} key={`${index} ${order.name}`} />
              ))
            }
          </>
        )
      default:
        break;
    }
  }

  useEffect(() => {
    if ( user === null ){
      router.push('/')
    }
  }, [])
  

  return (
    <div className='' >
      <Head>
        <title>Dashboard | Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full flex flex-col gap-5 items-center' >
        <div className='w-full h-fit flex items-center sticky top-12 z-20 bg-white' >
          <Button
            style={`tab__btn ${tab === "New" ? "primary__btn" : null} `}
            click={() => setTab("New")}
          >
            New
          </Button>
          <Button
            style={`tab__btn ${tab === "Reservation" ? "primary__btn" : null} `}
            click={() => setTab("Reservation")}>
            Reservation
          </Button>
          <Button
            style={`tab__btn ${tab === "Completed" ? "primary__btn" : null} `}
            click={() => setTab("Completed")}>
            Completed
          </Button>
          <Button
            style={`tab__btn ${tab === "Cancelled" ? "primary__btn" : null} `}
            click={() => setTab("Cancelled")}>
            Cancelled
          </Button>
        </div>
        <div className='w-full h-fit flex flex-col justify-start items-center ' >
          {handleTab()}
        </div>
      </main>
    </div>
  )
}

